name: Publish release

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  publish-release:
    runs-on: ubuntu-latest
    environment: release
    strategy:
      fail-fast: true
    permissions:
      contents: write
      packages: write

    steps:
      - name: Check branch
        if: ${{ github.ref != 'refs/heads/master' }}
        run: echo "Invalid branch. This action can only be run on the master branch." && exit 1

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PRESTODB_CI_TOKEN }}
          show-progress: false
          fetch-depth: 0
          ref: master

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
          cache: gradle

      - name: Set up git
        run: |
          git config --global --add safe.directory ${{github.workspace}}
          git config --global user.email "ci@lists.prestodb.io"
          git config --global user.name "prestodb-ci"
          git config pull.rebase false

      - name: Prepare release
        run: |
          mvn release:preare

      - name: Publish release
        run: |
          cat gradle.properties
          export NEXUS_USERNAME=${{ vars.NEXUS_USERNAME }}
          export NEXUS_PASSWORD=${{ secrets.NEXUS_PASSWORD }}
          mvn release:perform

      - name: Push changes and tags
        run: |
          git push origin master --tags
